import React, { useState } from "react";
import axios from "axios";
import { FiBarChart2, FiSearch, FiUsers } from "react-icons/fi";
import { SCHOOL_CLASSES, STREAMS } from "../../academicConfig";
import "./ModernMarkEntry.css";

const UNITS = ["Unit Test 1", "Unit Test 2", "Unit Test 3"];
const MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
export default function UnitTestSummary() {
  const [filters, setFilters] = useState({ academicYear: localStorage.getItem("activeSession") || "", class: "", stream: "", unit: "Unit Test 1", month: MONTHS[new Date().getMonth()] });
  const [data, setData] = useState({ subjects: [], rows: [] }), [message, setMessage] = useState(""), [loading, setLoading] = useState(false);
  const change = (e) => setFilters((old) => ({ ...old, [e.target.name]: e.target.value, ...(e.target.name === "class" ? { stream: "" } : {}) }));
  const load = async () => { if (!filters.class || (["11th", "12th"].includes(filters.class) && !filters.stream)) return setMessage("Class aur 11th/12th ke liye stream select karein."); setLoading(true); setMessage(""); try { const res = await axios.get("http://localhost:3000/unit-test-summary", { headers: { Authorization: `Bearer ${localStorage.getItem("token")}` }, params: filters }); setData(res.data); if (!res.data.subjects?.length) setMessage("Is unit test ka abhi koi subject record save nahi hai."); } catch (error) { setMessage(error.response?.data?.message || "Summary load nahi hui."); } finally { setLoading(false); } };
  return <main className="me-page"><header className="me-header"><div className="me-icon"><FiBarChart2 /></div><div><span>UNIT TEST REPORT</span><h2>Unit Test Summary</h2><p>Har subject aur total ka alag monthly record.</p></div></header>{message && <div className="me-alert error">{message}</div>}
  <section className="me-toolbar"><label><span>Class</span><select name="class" value={filters.class} onChange={change}><option value="">Select class</option>{SCHOOL_CLASSES.map((item) => <option key={item}>{item}</option>)}</select></label><label><span>Stream</span><select name="stream" value={filters.stream} onChange={change} disabled={!['11th','12th'].includes(filters.class)}><option value="">Select stream</option>{STREAMS.map((item) => <option key={item}>{item}</option>)}</select></label><label><span>Unit test</span><select name="unit" value={filters.unit} onChange={change}>{UNITS.map((item) => <option key={item}>{item}</option>)}</select></label><label><span>Month</span><select name="month" value={filters.month} onChange={change}>{MONTHS.map((item) => <option key={item}>{item}</option>)}</select></label><button type="button" onClick={load} disabled={loading}><FiSearch />{loading ? "Loading..." : "View summary"}</button></section>
  <section className="me-register"><div className="me-register-bar"><div><strong>{filters.unit} · {filters.month}</strong><span>{data.rows.length} students · {data.subjects.length} subjects</span></div></div><div className="me-table-wrap">{data.rows.length ? <table><thead><tr><th>#</th><th>Roll</th><th>Student</th>{data.subjects.map((subject) => <th key={subject}>{subject}</th>)}<th>Total</th></tr></thead><tbody>{data.rows.map((row, index) => <tr key={row.studentId}><td>{index + 1}</td><td>{row.rollNo || "—"}</td><td className="me-name">{row.name}</td>{data.subjects.map((subject) => <td key={subject}>{row.marks[subject] === "" ? "—" : row.marks[subject]}</td>)}<td><strong>{row.total}/{row.maximum}</strong></td></tr>)}</tbody></table> : <div className="me-empty"><FiUsers /><strong>Filters choose karke summary dekhein</strong></div>}</div></section></main>;
}
