import { useCallback, useEffect, useMemo, useState } from "react";
import axios from "axios";
import { FiCheckCircle, FiClipboard, FiDollarSign, FiRefreshCw, FiSearch } from "react-icons/fi";
import { SCHOOL_CLASSES } from "../../academicConfig";
import "./FeeReminders.css";
const money = (value) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value || 0);
export default function FeeReminders() {
  const session = localStorage.getItem("activeSession") || ""; const [studentClass, setStudentClass] = useState(""); const [query, setQuery] = useState(""); const [data, setData] = useState({ reminders: [], totalDue: 0, studentsDue: 0 }); const [loading, setLoading] = useState(true); const [copied, setCopied] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await axios.get("http://localhost:3000/fees/due-reminders", { params: { academicSession: session, studentClass }, headers: { Authorization: `Bearer ${localStorage.getItem("token")}` } }); setData(response.data); } catch (requestError) { setError(requestError.response?.data?.message || "Due reminders load nahi hue."); } finally { setLoading(false); } }, [session, studentClass]);
  useEffect(() => { load(); }, [load]);
  const visible = useMemo(() => { const term = query.trim().toLowerCase(); return term ? data.reminders.filter((row) => [row.name, row.admissionNo, row.phone, row.class].some((value) => String(value || "").toLowerCase().includes(term))) : data.reminders; }, [data.reminders, query]);
  const copy = async (text, id) => { await navigator.clipboard.writeText(text); setCopied(id); setTimeout(() => setCopied(""), 1500); };
  return <main className="reminder-page"><header className="reminder-hero"><div><span>FEES & COLLECTION</span><h1>Fee Due Reminders</h1><p>Pending ledger se parent-ready reminder text banayein aur copy karein.</p></div><button onClick={load}><FiRefreshCw/>Refresh</button></header>{error && <div className="reminder-error">{error}</div>}<section className="reminder-toolbar"><label>Class<select value={studentClass} onChange={(event) => setStudentClass(event.target.value)}><option value="">All classes</option>{SCHOOL_CLASSES.map((item) => <option key={item}>{item}</option>)}</select></label><label className="reminder-search"><span>Search</span><div><FiSearch/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Student, admission or phone"/></div></label></section><div className="reminder-stats"><div><span>Students with dues</span><strong>{data.studentsDue}</strong></div><div><span>Total pending</span><strong>{money(data.totalDue)}</strong></div><div><span>Visible reminders</span><strong>{visible.length}</strong></div></div>{loading ? <div className="reminder-empty">Fee ledgers check ho rahe hain...</div> : visible.length ? <div className="reminder-list">{visible.map((row) => <article key={row.studentId}><header><div><strong>{row.name}</strong><span>Class {row.class} · Adm. {row.admissionNo || "—"}</span></div><b>{money(row.balance)}</b></header><p>{row.message}</p><footer><span>{row.phone || "Phone not available"} · {row.billCount} pending bill(s)</span><button onClick={() => copy(row.message, row.studentId)}>{copied === row.studentId ? <FiCheckCircle/> : <FiClipboard/>}{copied === row.studentId ? "Copied" : "Copy reminder"}</button></footer></article>)}</div> : <div className="reminder-empty"><FiDollarSign/><span>Koi generated pending fee ledger nahi mila.</span></div>}</main>;
}