import { useCallback, useEffect, useMemo, useState } from "react";
import axios from "axios";
import { FiAlertTriangle, FiCheckCircle, FiRefreshCw, FiShuffle, FiUsers } from "react-icons/fi";
import { attendanceApi } from "../id-card/attendanceApi";
import "./StudentSync.css";

const clean = (value) => String(value || "").trim();
export default function StudentSync() {
  const [mongo, setMongo] = useState([]); const [sqlite, setSqlite] = useState([]); const [loading, setLoading] = useState(true); const [syncing, setSyncing] = useState(false); const [notice, setNotice] = useState(null);
  const session = localStorage.getItem("activeSession") || "";
  const load = useCallback(async () => { setLoading(true); setNotice(null); try { const [mongoResponse, sqliteResponse] = await Promise.all([axios.get("http://localhost:3000/all-idcards", { params: { academicSession: session }, headers: { Authorization: `Bearer ${localStorage.getItem("token")}` } }), attendanceApi.getStudents()]); setMongo(mongoResponse.data.students || []); setSqlite(sqliteResponse.students || []); } catch (error) { setNotice({ type: "error", text: error.response?.data?.message || error.message || "Sync preview load nahi hua." }); } finally { setLoading(false); } }, [session]);
  useEffect(() => { load(); }, [load]);
  const preview = useMemo(() => { const local = new Map(sqlite.map((student) => [clean(student.studentId).toLowerCase(), student])); const rows = mongo.map((student) => { const studentId = clean(student.admissionNo); if (!studentId) return { student, status: "invalid", details: "Admission No missing" }; const existing = local.get(studentId.toLowerCase()); if (!existing) return { student, studentId, status: "new", details: "SQLite me add hoga" }; const changed = clean(existing.name) !== clean(student.name) || clean(existing.className) !== clean(student.class) || clean(existing.academicSession) !== session; return { student, studentId, status: changed ? "changed" : "same", details: changed ? "Name/class/session update hoga" : "Already up to date" }; }); return { rows, newCount: rows.filter((r) => r.status === "new").length, changedCount: rows.filter((r) => r.status === "changed").length, invalidCount: rows.filter((r) => r.status === "invalid").length, sameCount: rows.filter((r) => r.status === "same").length }; }, [mongo, sqlite, session]);
  const sync = async () => { const candidates = preview.rows.filter((row) => row.status !== "invalid").map(({ student, studentId }) => ({ studentId, name: student.name, className: student.class, fatherName: student.fatherName, phone: student.phone })); if (!candidates.length) return; if (!window.confirm(`${candidates.length} MongoDB students ko isolated SQLite roster me sync karein? MongoDB data change nahi hoga.`)) return; setSyncing(true); try { const result = await attendanceApi.syncStudents(candidates, session); setNotice({ type: "success", text: result.message }); await load(); } catch (error) { setNotice({ type: "error", text: error.message }); } finally { setSyncing(false); } };
  return <main className="sync-page"><header className="sync-hero"><div><span>CONTROLLED DATA BRIDGE</span><h1>MongoDB → SQLite Student Sync</h1><p>Preview ke baad ERP students ko ID/QR attendance roster me copy karein. MongoDB source unchanged rahega.</p></div><button onClick={load} disabled={loading}><FiRefreshCw/>Refresh</button></header>{notice && <div className={`sync-notice ${notice.type}`}>{notice.type === "success" ? <FiCheckCircle/> : <FiAlertTriangle/>}{notice.text}</div>}{loading ? <div className="sync-loading">Dono databases compare ho rahe hain...</div> : <><section className="sync-stats"><div><span>MongoDB</span><strong>{mongo.length}</strong></div><div><span>New</span><strong>{preview.newCount}</strong></div><div><span>Changed</span><strong>{preview.changedCount}</strong></div><div><span>Unchanged</span><strong>{preview.sameCount}</strong></div><div className="invalid"><span>Blocked</span><strong>{preview.invalidCount}</strong></div></section><section className="sync-card"><header><div><FiUsers/><span><strong>Sync preview</strong><small>Session {session || "not selected"}</small></span></div><button onClick={sync} disabled={syncing || !session || mongo.length === preview.invalidCount}><FiShuffle/>{syncing ? "Syncing..." : "Confirm & sync roster"}</button></header><div className="sync-table"><table><thead><tr><th>Student</th><th>Admission No</th><th>Class</th><th>Result</th></tr></thead><tbody>{preview.rows.map(({ student, studentId, status, details }, index) => <tr key={student._id || index}><td><strong>{student.name}</strong><small>{student.fatherName || "—"}</small></td><td>{studentId || "—"}</td><td>{student.class || "—"}</td><td><span className={`sync-status ${status}`}>{details}</span></td></tr>)}</tbody></table></div></section></>}
  </main>;
}