import { useCallback, useEffect, useState } from "react";
import axios from "axios";
import { FiActivity, FiRefreshCw, FiSave, FiShield, FiUsers } from "react-icons/fi";
import "./UserAccess.css";
const roles = ["admin", "principal", "teacher", "accountant", "operator", "student"];
const permissions = ["students.manage", "attendance.manage", "fees.manage", "exams.manage", "documents.manage", "idcards.manage", "reports.view"];
const headers = () => ({ Authorization: `Bearer ${localStorage.getItem("token")}` });
export default function UserAccess() {
  const [tab, setTab] = useState("users"); const [users, setUsers] = useState([]); const [logs, setLogs] = useState([]); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { setLoading(true); setNotice(""); try { const endpoint = tab === "users" ? "/admin/users" : "/admin/audit-logs"; const { data } = await axios.get(`http://localhost:3000${endpoint}`, { headers: headers() }); if (tab === "users") setUsers(data.users || []); else setLogs(data.logs || []); } catch (error) { setNotice(error.response?.data?.message || "Admin data load nahi hua."); } finally { setLoading(false); } }, [tab]);
  useEffect(() => { load(); }, [load]);
  const updateLocal = (id, patch) => setUsers((current) => current.map((user) => user._id === id ? { ...user, ...patch } : user));
  const save = async (user) => { try { const { data } = await axios.put(`http://localhost:3000/admin/users/${user._id}/access`, { role: user.role, active: user.active !== false, permissions: user.permissions || [] }, { headers: headers() }); updateLocal(user._id, data.user); setNotice(data.message); } catch (error) { setNotice(error.response?.data?.message || "User access save nahi hua."); } };
  const togglePermission = (user, permission) => { const current = user.permissions || []; updateLocal(user._id, { permissions: current.includes(permission) ? current.filter((item) => item !== permission) : [...current, permission] }); };
  return <main className="access-page"><header className="access-hero"><div><span>SECURITY & ACCOUNTABILITY</span><h1>User Permissions & Audit Log</h1><p>Roles, account access aur system changes ko ek jagah manage karein.</p></div><button onClick={load}><FiRefreshCw/>Refresh</button></header><nav className="access-tabs"><button className={tab === "users" ? "active" : ""} onClick={() => setTab("users")}><FiUsers/>User access</button><button className={tab === "audit" ? "active" : ""} onClick={() => setTab("audit")}><FiActivity/>Audit log</button></nav>{notice && <div className="access-notice">{notice}</div>}{loading ? <div className="access-loading">Loading...</div> : tab === "users" ? <div className="user-access-list">{users.map((user) => <article key={user._id}><header><div><FiShield/><span><strong>{user.username}</strong><small>{user.email}</small></span></div><label><input type="checkbox" checked={user.active !== false} onChange={(event) => updateLocal(user._id, { active: event.target.checked })}/>Active</label></header><div className="user-role"><label>Role<select value={user.role} onChange={(event) => updateLocal(user._id, { role: event.target.value })}>{roles.map((role) => <option key={role}>{role}</option>)}</select></label><button onClick={() => save(user)}><FiSave/>Save access</button></div><div className="permission-grid">{permissions.map((permission) => <label key={permission}><input type="checkbox" checked={(user.permissions || []).includes(permission)} onChange={() => togglePermission(user, permission)}/>{permission.replace(".", " ")}</label>)}</div></article>)}</div> : <div className="audit-table"><table><thead><tr><th>Time</th><th>User</th><th>Role</th><th>Action</th><th>Status</th></tr></thead><tbody>{logs.map((log) => <tr key={log._id}><td>{new Date(log.createdAt).toLocaleString("en-IN")}</td><td>{log.username || log.userId || "System"}</td><td>{log.role || "—"}</td><td><strong>{log.method}</strong> {log.path}</td><td>{log.statusCode}</td></tr>)}</tbody></table></div>}</main>;
}