import { useEffect, useMemo, useState } from "react";
import axios from "axios";
import { FiCalendar, FiCheck, FiClock, FiSearch, FiUsers } from "react-icons/fi";
import { SCHOOL_CLASSES } from "../../academicConfig";
import "./Attendence.css";

const today = () => new Date().toLocaleDateString("en-CA");
export default function ClassAttendance() {
  const session=localStorage.getItem("activeSession")||""; const teacher=localStorage.getItem("username")||"Faculty";
  const [studentClass,setStudentClass]=useState(""); const [date,setDate]=useState(today()); const [students,setStudents]=useState([]); const [attendance,setAttendance]=useState({}); const [search,setSearch]=useState(""); const [loading,setLoading]=useState(false); const [saving,setSaving]=useState(false); const [notice,setNotice]=useState(null);
  useEffect(()=>{if(!studentClass){setStudents([]);setAttendance({});return;}const controller=new AbortController();(async()=>{setLoading(true);setNotice(null);try{const headers={Authorization:`Bearer ${localStorage.getItem("token")}`};const [roster,day]=await Promise.all([axios.get("http://localhost:3000/all-students",{signal:controller.signal,headers,params:{studentClass,academicSession:session,search:""}}),axios.get("http://localhost:3000/attendance",{signal:controller.signal,headers,params:{date,academicSession:session,studentClass}})]);setStudents(roster.data||[]);const statuses={};(day.data.students||[]).forEach(item=>{statuses[item.studentId]=item.status});setAttendance(statuses);}catch(error){if(error.code!=="ERR_CANCELED")setNotice({type:"error",text:error.response?.data?.message||"Attendance register load nahi hua."});}finally{setLoading(false);}})();return()=>controller.abort();},[studentClass,date,session]);
  const visible=useMemo(()=>students.filter(s=>s.name?.toLowerCase().includes(search.trim().toLowerCase())||String(s.rollNo||"").includes(search)),[students,search]); const counts=students.reduce((a,s)=>{a[attendance[s._id]||"Absent"]++;return a;},{Present:0,Absent:0,Late:0});
  const setAll=status=>setAttendance(Object.fromEntries(students.map(s=>[s._id,status])));
  const save=async()=>{if(!studentClass||!students.length)return;setSaving(true);setNotice(null);try{const attendanceData=students.map(s=>({studentId:s._id,class:studentClass,date,status:attendance[s._id]||"Absent",markedBy:teacher,source:"manual"}));const {data}=await axios.post("http://localhost:3000/student-attendance",{attendanceData,academicSession:session},{headers:{Authorization:`Bearer ${localStorage.getItem("token")}`}});setNotice({type:"success",text:data.message||"Attendance save ho gayi."});}catch(error){setNotice({type:"error",text:error.response?.data?.message||"Attendance save nahi hui."});}finally{setSaving(false)}};
  return <main className="ma-page"><header className="ma-header"><div className="ma-icon"><FiCheck/></div><div><span>TEACHER PANEL</span><h2>Manual Attendance</h2><p>MongoDB roster · QR aur manual entry ek hi unified register mein save hoti hai.</p></div><div className="ma-session"><small>Active session</small><strong>{session||"Not selected"}</strong></div></header>{notice&&<div className={`ma-notice ${notice.type}`}>{notice.text}</div>}<section className="ma-toolbar"><label><span>Class</span><select value={studentClass} onChange={e=>setStudentClass(e.target.value)}><option value="">Select class</option>{SCHOOL_CLASSES.map(c=><option key={c}>{c}</option>)}</select></label><label><span>Date</span><div><FiCalendar/><input type="date" value={date} max={today()} onChange={e=>setDate(e.target.value)}/></div></label><label className="ma-search"><span>Find student</span><div><FiSearch/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or roll" disabled={!students.length}/></div></label></section><section className="ma-stats"><div><FiUsers/><span>Total<strong>{students.length}</strong></span></div><div className="present"><FiCheck/><span>Present<strong>{counts.Present}</strong></span></div><div className="absent"><span>A</span><span>Absent<strong>{counts.Absent}</strong></span></div><div className="late"><FiClock/><span>Late<strong>{counts.Late}</strong></span></div><aside><button onClick={()=>setAll("Present")} disabled={!students.length}>All present</button><button onClick={()=>setAll("Absent")} disabled={!students.length}>All absent</button></aside></section><section className="ma-register"><div className="ma-table-wrap">{loading?<div className="ma-empty">Register load ho raha hai...</div>:visible.length?<table><thead><tr><th>Roll</th><th>Student</th><th>Father</th><th>Status</th></tr></thead><tbody>{visible.map(s=><tr key={s._id}><td>{s.rollNo||"?"}</td><td><strong>{s.name}</strong><small>{s.admissionNo||""}</small></td><td>{s.fatherName||"?"}</td><td><div className="ma-status">{["Present","Absent","Late"].map(status=><button key={status} className={(attendance[s._id]||"Absent")===status?status.toLowerCase():""} onClick={()=>setAttendance(p=>({...p,[s._id]:status}))}>{status}</button>)}</div></td></tr>)}</tbody></table>:<div className="ma-empty">Class select karke MongoDB students load karein.</div>}</div>{students.length>0&&<footer><span>{date} ? {teacher}</span><button onClick={save} disabled={saving}>{saving?"Saving...":"Save attendance"}</button></footer>}</section></main>;
}
