import { useCallback, useEffect, useMemo, useState } from "react";
import axios from "axios";
import { useNavigate } from "react-router-dom";
import { FiBriefcase, FiDollarSign, FiEdit2, FiPlus, FiSearch, FiTrash2, FiUsers, FiX } from "react-icons/fi";
import "./TeacherManagement.css";

const API = "http://localhost:3000";
const headers = () => ({ Authorization: `Bearer ${localStorage.getItem("token")}` });
const money = (value) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Number(value || 0));
const blank = { employeeId: "", name: "", phone: "", email: "", gender: "", joiningDate: new Date().toISOString().slice(0, 10), designation: "Teacher", qualification: "", subjects: "", classes: "", address: "", bankName: "", accountNo: "", ifsc: "", monthlySalary: "", status: "Active" };

export default function TeacherManagement() {
  const navigate = useNavigate(); const [image, setImage] = useState(null);
  const [teachers, setTeachers] = useState([]); const [summary, setSummary] = useState({}); const [search, setSearch] = useState("");
  const [form, setForm] = useState(blank); const [editing, setEditing] = useState(null); const [showForm, setShowForm] = useState(false); const [selected, setSelected] = useState(null);
  const [payment, setPayment] = useState({ month: new Date().toISOString().slice(0, 7), amount: "", mode: "Bank Transfer", note: "" }); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const { data } = await axios.get(`${API}/teachers`, { headers: headers(), params: { status: "Active" } }); setTeachers(data.teachers); setSummary(data.summary); setSelected((current) => current ? data.teachers.find((t) => t._id === current._id) || null : null); } catch (e) { setNotice(e.response?.data?.message || "Teacher records load nahi hue."); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const rows = useMemo(() => teachers.filter((t) => [t.name, t.employeeId, t.phone, t.designation].some((x) => String(x || "").toLowerCase().includes(search.toLowerCase()))), [teachers, search]);
  const edit = (teacher) => { setEditing(teacher._id); setForm({ ...blank, ...teacher, joiningDate: teacher.joiningDate?.slice(0, 10), subjects: teacher.subjects?.join(", "), classes: teacher.classes?.join(", ") }); setShowForm(true); };
  const save = async (event) => { event.preventDefault(); const dataForm = new FormData(); Object.entries({ ...form, monthlySalary: Number(form.monthlySalary), subjects: JSON.stringify(form.subjects.split(",").map((x) => x.trim()).filter(Boolean)), classes: JSON.stringify(form.classes.split(",").map((x) => x.trim()).filter(Boolean)) }).forEach(([key, value]) => dataForm.append(key, value ?? "")); if (image) dataForm.append("image", image); try { const url = `${API}/teachers${editing ? `/${editing}` : ""}`; const { data } = await axios({ method: editing ? "put" : "post", url, data: dataForm, headers: headers() }); setNotice(data.message); setShowForm(false); setEditing(null); setImage(null); setForm(blank); load(); } catch (e) { setNotice(e.response?.data?.message || "Profile save nahi hua."); } };
  const pay = async (event) => { event.preventDefault(); try { const { data } = await axios.post(`${API}/teachers/${selected._id}/payments`, payment, { headers: headers() }); setNotice(data.message); setSelected(data.teacher); setPayment({ ...payment, amount: "", note: "" }); load(); } catch (e) { setNotice(e.response?.data?.message || "Payment save nahi hui."); } };
  const removePayment = async (id) => { if (!confirm("Is salary payment ko delete karein?")) return; try { const { data } = await axios.delete(`${API}/teachers/${selected._id}/payments/${id}`, { headers: headers() }); setNotice(data.message); load(); } catch (e) { setNotice(e.response?.data?.message || "Payment delete nahi hui."); } };
  const changeTeacherStatus = async (teacher) => { try { if (teacher.status === "Active") { if (!confirm(`${teacher.name} school chhod chuke hain? Record delete nahi hoga; sirf inactive mark hoga.`)) return; const exitReason = prompt("Leaving reason (optional):", "School left") || "School left"; const { data } = await axios.delete(`${API}/teachers/${teacher._id}`, { headers: headers(), data: { exitReason, leftAt: new Date() } }); setNotice(data.message); } else { if (!confirm(`${teacher.name} ko dobara active karein?`)) return; const { data } = await axios.patch(`${API}/teachers/${teacher._id}/reactivate`, {}, { headers: headers() }); setNotice(data.message); } await load(); } catch (e) { setNotice(e.response?.data?.message || "Teacher status update nahi hua."); } };

  return <div className="teacher-page">
    <header><div><span className="eyebrow">STAFF & PAYROLL</span><h1>Teacher Management</h1><p>Teacher profiles, bank details aur salary payments ek jagah manage karein.</p></div><button className="primary" onClick={() => { setEditing(null); setForm(blank); setShowForm(true); }}><FiPlus /> Add Teacher</button></header>
    {notice && <div className="notice" onClick={() => setNotice("")}>{notice}<FiX /></div>}
    <section className="stats"><article><FiUsers /><div><span>Total Teachers</span><strong>{summary.total || 0}</strong></div></article><article><FiBriefcase /><div><span>Active Staff</span><strong>{summary.active || 0}</strong></div></article><article><FiDollarSign /><div><span>Monthly Payroll</span><strong>{money(summary.monthlyPayroll)}</strong></div></article><article><FiDollarSign /><div><span>Total Paid</span><strong>{money(summary.paid)}</strong></div></article></section>
    <section className="panel"><div className="toolbar"><div className="search"><FiSearch /><input placeholder="Name, employee ID, phone..." value={search} onChange={(e) => setSearch(e.target.value)} /></div><span>{rows.length} records</span></div>
      <div className="teacher-grid">{rows.map((teacher) => <article className="teacher-card" key={teacher._id}><div className="avatar" onClick={() => navigate(`/dashboard/teachers/${teacher._id}`)}>{teacher.image ? <img src={`${API}/uploads/${teacher.image}`} alt={teacher.name} /> : teacher.name.slice(0, 2).toUpperCase()}</div><div className="teacher-info"><div><h3 onClick={() => navigate(`/dashboard/teachers/${teacher._id}`)} style={{ cursor: "pointer" }}>{teacher.name}</h3><span className={`status ${teacher.status.toLowerCase()}`}>{teacher.status}</span></div><p>{teacher.designation} · {teacher.employeeId}</p><small>{teacher.subjects?.join(", ") || "Subjects not assigned"}</small><div className="salary"><span>Monthly salary</span><strong>{money(teacher.monthlySalary)}</strong></div><div className="actions"><button onClick={() => setSelected(teacher)}><FiDollarSign /> Pay / History</button><button onClick={() => edit(teacher)}><FiEdit2 /> Edit</button><button className={teacher.status === "Active" ? "leave-button" : "reactivate-button"} onClick={() => changeTeacherStatus(teacher)}>{teacher.status === "Active" ? <><FiTrash2 /> School Left</> : <><FiUsers /> Reactivate</>}</button></div>{teacher.status === "Inactive" && <div className="inactive-note">Inactive{teacher.leftAt ? ` since ${new Date(teacher.leftAt).toLocaleDateString("en-IN")}` : ""} · Payment history preserved</div>}</div></article>)}</div>{!loading && !rows.length && <div className="empty">Koi teacher record nahi mila. Pehla teacher add karein.</div>}
    </section>
    {showForm && <div className="modal"><form className="dialog profile-form" onSubmit={save}><div className="dialog-head"><div><span className="eyebrow">PROFILE</span><h2>{editing ? "Edit Teacher" : "Add New Teacher"}</h2></div><button type="button" className="icon" onClick={() => setShowForm(false)}><FiX /></button></div><div className="form-grid">
      {[['employeeId','Employee ID (Auto)','text'],['name','Full Name','text'],['phone','Phone','tel'],['email','Email','email'],['joiningDate','Joining Date','date'],['designation','Designation','text'],['qualification','Qualification','text'],['monthlySalary','Monthly Salary','number'],['subjects','Subjects (comma separated)','text'],['classes','Classes (comma separated)','text'],['bankName','Bank Name','text'],['accountNo','Account Number','text'],['ifsc','IFSC Code','text']].map(([key,label,type]) => <label key={key}><span>{label}</span><input type={type} value={key === "employeeId" && !editing ? "Auto-generated on save" : (form[key] || "")} readOnly={key === "employeeId"} required={['name','phone','joiningDate','designation','monthlySalary'].includes(key)} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></label>)}
      <label className="wide"><span>Profile Photo</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => setImage(e.target.files[0] || null)} /></label><label><span>Gender</span><select value={form.gender} onChange={(e) => setForm({ ...form, gender: e.target.value })}><option value="">Select</option><option>Male</option><option>Female</option><option>Other</option></select></label><label><span>Status</span><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option>Active</option><option>Inactive</option></select></label><label className="wide"><span>Address</span><textarea value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} /></label></div><div className="form-actions"><button type="button" onClick={() => setShowForm(false)}>Cancel</button><button className="primary">Save Teacher</button></div></form></div>}
    {selected && <div className="modal"><div className="dialog pay-dialog"><div className="dialog-head"><div><span className="eyebrow">SALARY LEDGER</span><h2>{selected.name}</h2><p>{selected.employeeId} · {money(selected.monthlySalary)} / month</p></div><button className="icon" onClick={() => setSelected(null)}><FiX /></button></div><form className="pay-form" onSubmit={pay}><label>Salary Month<input type="month" required value={payment.month} onChange={(e) => setPayment({ ...payment, month: e.target.value })} /></label><label>Amount<input type="number" min="1" required value={payment.amount} onChange={(e) => setPayment({ ...payment, amount: e.target.value })} /></label><label>Mode<select value={payment.mode} onChange={(e) => setPayment({ ...payment, mode: e.target.value })}>{["Bank Transfer","Cash","UPI","Cheque","Other"].map((x) => <option key={x}>{x}</option>)}</select></label><label>Note<input value={payment.note} onChange={(e) => setPayment({ ...payment, note: e.target.value })} /></label><button className="primary">Record Payment</button></form><div className="history"><h3>Payment History</h3>{[...(selected.payments || [])].reverse().map((p) => <div className="history-row" key={p._id}><div><strong>{money(p.amount)}</strong><span>{p.month} · {p.mode}</span></div><div><small>{p.receiptNo}</small><button onClick={() => removePayment(p._id)}><FiTrash2 /></button></div></div>)}{!selected.payments?.length && <p className="empty">Abhi koi payment record nahi hai.</p>}</div></div></div>}
  </div>;
}



