import { useCallback, useEffect, useMemo, useState } from "react";
import axios from "axios";
import { QRCodeSVG } from "qrcode.react";
import { useNavigate, useParams } from "react-router-dom";
import { FiArrowLeft, FiBriefcase, FiCalendar, FiCheckCircle, FiClock, FiDollarSign, FiMail, FiMapPin, FiPhone, FiUser } from "react-icons/fi";
import "./TeacherDetail.css";
const API="http://localhost:3000"; const auth=()=>({Authorization:`Bearer ${localStorage.getItem("token")}`}); const money=(v)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(v||0));
export default function TeacherDetail(){const {id}=useParams();const navigate=useNavigate();const [teacher,setTeacher]=useState(null);const [attendance,setAttendance]=useState([]);const [tab,setTab]=useState("overview");const load=useCallback(async()=>{const [profile,records]=await Promise.all([axios.get(`${API}/teachers/${id}`,{headers:auth()}),axios.get(`${API}/teacher-attendance`,{headers:auth(),params:{teacherId:id}})]);setTeacher(profile.data.teacher);setAttendance(records.data.records)},[id]);useEffect(()=>{load().catch(()=>navigate("/dashboard/teachers"))},[load,navigate]);const attendanceSummary=useMemo(()=>({present:attendance.filter(x=>["Present","Late"].includes(x.status)).length,absent:attendance.filter(x=>x.status==="Absent").length,leave:attendance.filter(x=>["Leave","Half Day"].includes(x.status)).length}),[attendance]);if(!teacher)return <div className="teacher-detail-loading">Loading teacher profile...</div>;return <main className="teacher-detail-page"><button className="detail-back" onClick={()=>navigate(-1)}><FiArrowLeft/>Back</button><section className="profile-banner"><div className="profile-photo">{teacher.image?<img src={`${API}/uploads/${teacher.image}`} alt={teacher.name}/>:teacher.name.slice(0,2).toUpperCase()}</div><div className="profile-title"><span>{teacher.employeeId}</span><h1>{teacher.name}</h1><p><FiBriefcase/> {teacher.designation} Â· {teacher.subjects?.join(", ")||"No subject assigned"}</p></div><div className={`profile-status ${teacher.status.toLowerCase()}`}><FiCheckCircle/><span>{teacher.status}{teacher.leftAt && <small>Left {new Date(teacher.leftAt).toLocaleDateString("en-IN")} Â· {teacher.exitReason || "School left"}</small>}</span></div></section><nav className="detail-tabs">{[["overview","Full Profile"],["payments","Payment History"],["attendance","Attendance History"]].map(([key,label])=><button className={tab===key?"active":""} onClick={()=>setTab(key)} key={key}>{label}</button>)}</nav>
{tab==="overview"&&<div className="detail-grid"><section className="detail-card"><h2><FiUser/>Personal details</h2><dl><div><dt>Phone</dt><dd><FiPhone/>{teacher.phone}</dd></div><div><dt>Email</dt><dd><FiMail/>{teacher.email||"â€”"}</dd></div><div><dt>Gender</dt><dd>{teacher.gender||"â€”"}</dd></div><div><dt>Address</dt><dd><FiMapPin/>{teacher.address||"â€”"}</dd></div></dl></section><section className="detail-card"><h2><FiBriefcase/>Professional details</h2><dl><div><dt>Joining date</dt><dd>{new Date(teacher.joiningDate).toLocaleDateString("en-IN")}</dd></div><div><dt>Qualification</dt><dd>{teacher.qualification||"â€”"}</dd></div><div><dt>Classes</dt><dd>{teacher.classes?.join(", ")||"â€”"}</dd></div><div><dt>Monthly salary</dt><dd>{money(teacher.monthlySalary)}</dd></div></dl></section><section className="detail-card wide"><h2><FiDollarSign/>Bank details</h2><dl className="bank-grid"><div><dt>Bank</dt><dd>{teacher.bankName||"â€”"}</dd></div><div><dt>Account number</dt><dd>{teacher.accountNo||"â€”"}</dd></div><div><dt>IFSC</dt><dd>{teacher.ifsc||"â€”"}</dd></div></dl></section></div>}
{tab==="payments"&&<section className="history-card"><div className="history-summary"><div><span>Total payments</span><strong>{teacher.payments?.length||0}</strong></div><div><span>Total amount paid</span><strong>{money(teacher.payments?.reduce((s,p)=>s+Number(p.amount),0))}</strong></div></div><div className="timeline">{[...(teacher.payments||[])].reverse().map(p=><article key={p._id}><div className="timeline-icon"><FiDollarSign/></div><div><strong>{money(p.amount)}</strong><p>Salary for {p.month} Â· {p.mode}</p><small>{p.receiptNo} Â· {new Date(p.date).toLocaleDateString("en-IN")}</small>{p.note&&<em>{p.note}</em>}</div></article>)}{!teacher.payments?.length&&<p className="empty-detail">No payment history available.</p>}</div></section>}
{tab==="attendance"&&<section className="history-card"><div className="history-summary attendance"><div><span>Present / Late</span><strong>{attendanceSummary.present}</strong></div><div><span>Absent</span><strong>{attendanceSummary.absent}</strong></div><div><span>Leave / Half day</span><strong>{attendanceSummary.leave}</strong></div></div><div className="attendance-list">{attendance.map(record=><article key={record._id}><div><FiCalendar/><strong>{new Date(record.date+"T00:00:00").toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"})}</strong></div><span className={`attendance-badge ${record.status.toLowerCase().replace(" ","-")}`}>{record.status}</span><small><FiClock/>{record.checkIn||"â€”"} to {record.checkOut||"â€”"}</small><p>{record.note||""}</p></article>)}{!attendance.length&&<p className="empty-detail">No attendance records available.</p>}</div></section>}</main>}

