use serde::{Deserialize, Serialize}; use sha2::{Digest, Sha256}; use winreg::{enums::{HKEY_CURRENT_USER,HKEY_LOCAL_MACHINE},RegKey};
const PRODUCT:&str="vidyaprabandh-offline-desktop"; const API:&str="https://vidyaprabandh.in/api"; const PATH:&str="Software\\Vidyaprabandh\\Offline Desktop";
#[derive(Serialize,Deserialize)] struct State{device_token:String}
#[derive(Serialize)] #[serde(rename_all="camelCase")] pub struct Status{days_left:i64,expired:bool,reason:Option<String>,activation_required:bool}
#[derive(Deserialize)] #[serde(rename_all="camelCase")] struct Api{active:bool,days_left:Option<i64>,reason:Option<String>,error:Option<String>,device_token:Option<String>}
fn machine()->Result<String,String>{let k=RegKey::predef(HKEY_LOCAL_MACHINE).open_subkey("SOFTWARE\\Microsoft\\Cryptography").map_err(|_|"Machine ID unavailable.".to_string())?;let g:String=k.get_value("MachineGuid").map_err(|_|"Machine ID unavailable.".to_string())?;Ok(format!("{:x}",Sha256::digest(format!("{PRODUCT}:{g}").as_bytes())).to_uppercase())}
fn read()->Result<Option<State>,String>{let(k,_)=RegKey::predef(HKEY_CURRENT_USER).create_subkey(PATH).map_err(|e|e.to_string())?;match k.get_value::<String,_>("ServerActivationV1"){Ok(s)=>serde_json::from_str(&s).map(Some).map_err(|_|"Saved activation is invalid.".into()),Err(e)if e.kind()==std::io::ErrorKind::NotFound=>Ok(None),Err(e)=>Err(e.to_string())}}
fn save(s:&State)->Result<(),String>{let(k,_)=RegKey::predef(HKEY_CURRENT_USER).create_subkey(PATH).map_err(|e|e.to_string())?;k.set_value("ServerActivationV1",&serde_json::to_string(s).unwrap()).map_err(|e|e.to_string())}
fn post(path:&str,body:serde_json::Value)->Result<Api,String>{reqwest::blocking::Client::builder().timeout(std::time::Duration::from_secs(12)).build().map_err(|_|"Secure connection unavailable.".to_string())?.post(format!("{API}/{path}")).json(&body).send().map_err(|_|"Internet or licence service unavailable.".to_string())?.json().map_err(|_|"Invalid licence response.".to_string())}
fn status(a:Api)->Status{let r=a.reason.or(a.error);Status{days_left:a.days_left.unwrap_or(0).max(0),expired:!a.active,reason:if a.active{None}else{r.or(Some("Licence is unavailable.".into()))},activation_required:false}}
#[tauri::command] pub fn demo_status()->Result<Status,String>{let Some(s)=read()? else{return Ok(Status{days_left:0,expired:true,reason:Some("Enter your Vidyaprabandh activation key.".into()),activation_required:true})};Ok(status(post("status.php",serde_json::json!({"machineId":machine()?,"deviceToken":s.device_token,"product":PRODUCT}))?))}
#[tauri::command] pub fn activate_demo(activation_key:String)->Result<Status,String>{let a=post("activate.php",serde_json::json!({"licenseKey":activation_key.trim(),"machineId":machine()?,"product":PRODUCT}))?;if !a.active{return Ok(status(a))}let t=a.device_token.clone().ok_or("Missing device token.")?;save(&State{device_token:t})?;Ok(status(a))}
